config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :planets, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:create, :new, :update, :edit, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  # belongs_to :user
  # belongs_to :planet

  #validates :check_in_date, :check_out_date, :price, :location, :number_of_guests, presence: true
  validates :check_in_date, :check_out_date, :number_of_guests, presence: true
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :bookings
  belongs_to :user

  validates :price, :title, presence: true
  has_many_attached :photos

  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
    against: [ :title, :description ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @planet = Planet.find(params[:planet_id])
    @booking = Booking.new(booking_params)
    @booking.planet = @planet
    @booking.user = current_user
    @booking.save!
    redirect_to edit_planet_booking_path(@planet, @booking)
    # else 
    #   render ''
    # end
  end

  def new
    @booking =Booking.new
    
  end

  def edit
    @planet = Planet.find(params[:planet_id])
    @booking =Booking.find(params[:id])
  end

  def update
    @booking =Booking.find(params[:id])
    @booking.update(booking_params)
    @booking.save
      redirect_to planet_booking_path(@booking.planet, @booking)
  end

  def show
    @booking =Booking.find(params[:id])
  end

  private
  def booking_params
    params.require(:booking).permit(:check_in_date, :check_out_date, :price, :location, :number_of_guests, :first_name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController

  before_action :set_planet, only: [:show]

  def index
    if params[:query].present?
      @planets = Planet.search_by_title_and_description(params[:query])
    else
      @planets = Planet.all
    end
    # planets = [ 
    #   'NES',
    #   'Jedha'
    # ]
    #render(json: { 'planets' => @planets.map(&:title) })
  end

  def show
    @booking = Booking.new
  end

  def new
    @planet = Planet.new
  end

  def create
    @planet = Planet.new(planet_params)
    @planet.user = current_user
    if @planet.save
      flash[:notice] = "Planet has been created"
      redirect_to planet_path(@planet)
    else
      flash[:alert] = "Planet has not been created"
      render "new"
    end
  end

  private
  def set_planet
    @planet = Planet.find(params[:id])
  end

  def planet_params
    params.require(:planet).permit(:price, :title, :description, :name_of_inhabitants,
      :name_of_space_station, :name_of_galaxy, :host_name, photos: [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
  
<div class="container booking-form">
    <div class="card">
      <span><strong>$<%= @planet.price %></strong> /night</span>
      <%= simple_form_for [@planet, @booking] do |f| %>
        <%= f.input :price, as: :hidden, input_html: {value: @planet.price } %>
        <%= f.input :check_in_date, as: :string, label: false, placeholder: 'Check in',  input_html: {class: "datepicker", :onchange => "handleBookingFormChange(event)"}%>
        <%= f.input :check_out_date, as: :string, label: false, placeholder: 'Check out', input_html: {class: "datepicker", :onchange => "handleBookingFormChange(event)"} %>
        <%= f.input :number_of_guests, label: false, placeholder: 'Space Travellers', class: "w-100", input_html: {:onchange => "handleBookingFormChange(event)"} %>
        <div class="d-flex justify-content-between">
          <span>Total:</span>
          <span class="total"></span>
        </div>
        <%= f.button :button, "Instant Book", class: "button w-100 mt-2" %>
        <div><%= f.button :button, "Contact Host", class: "button-white w-100" %></div>
      <% end %>
</div>

app/views/bookings/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3">
      <div class="bg-white rounded p-3 shadow confirmation mt-3 mb-3">
        <h3 class= "mb-4">Complete your booking</h3>
        <%= simple_form_for [@planet, @booking] do |f| %>
          <div class="form-row">
            <div class="form-group col-md-6">
              <%= f.input :first_name, label: false, placeholder: 'First Name' %>
            </div>
            <div class="form-group col-md-6">
              <%= f.input :last_name, label: false, placeholder: 'Last Name' %>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <%= f.input :email, label: false, placeholder: 'Email Address' %>
            </div>
            <div class="form-group col-md-6">
              <%= f.input :phone_number, label: false, placeholder: 'Phone Number' %>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-lg-9">
              <%= f.input :credit_card, label: false, placeholder: 'Credit Card' %>
            </div>
            <div class="form-group col-md-3">
              <%= f.input :credit_card_expiration_date, label: false, placeholder: 'MM/YY' %>
            </div>
          </div>
          <%= f.input :message, as: :text, label: "Message Your Host (optional)", placeholder: "Give a brief description of yourself, who you are travelling with, or any special requests you may have.",  :input_html => { :cols => 5, :rows => 8 } %>

           <p><small><em class="text-muted">By clicking <strong>'Confirm'</strong> you are agreeing to our Terms & Conditions, Privacy Policy, and to received booking-related messages.</em></small></p>
           <%= f.button :button, "Confirm", class: "button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container mt-5 p-4 confirmation-view">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3 card-confirmation">
    
      <h2 class="booking-h1">Great <strong><%= @booking.first_name %></strong>,</h2>
      <h2 class="booking-h1">Your booking has been confirmed</h2>
      <p>You will receive a confirmation email soon with your booking details.</p>
      <br>
      <div class="container">
        <div class="row d-flex justify-content-between">
          <div>
            <p><i class="fas fa-globe-africa"></i>  <%= @booking.planet.title %></p>
            <br>
            <i class="fas fa-user-friends"></i> <%= @booking.number_of_guests %>
          </div>
          <div>
            <i class="far fa-calendar-alt"></i> <%= @booking.check_in_date.strftime('%m/%d/%Y')%> - <%= @booking.check_out_date.strftime('%m/%d/%Y') %>
          </div>
        </div>
        <a class="button m-5" href="#">View Booking</a>
      </div>
   
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pianeta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application'%>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%#= render 'shared/navbar' %>
    <% if current_page?(root_path) %>
<%=  %>
<% else %>
<%= render 'shared/navbar' %>
<% end %>
   <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!--<canvas id="granim-canvas"></canvas>-->
<div class="container_home_page text-center">
    <div class="planet_one granim-gradient newly-added"></div>
    <div class="card-white text-center" id="introduction">
        <h1 class="title_home_page newly-added">Pianeta</h1>
        <div class="white-line newly-added"></div>
        </div>
        <div class= "card-description">
        <p class="homepage newly-added">
        Space is full of surprises. Pianeta offers space travellers an array of Planet destinations that everyone dreams of visiting, anywhere in the universe. Ready to sail the stars on the way to discovering infinity and beyond?
        <br>
        <br>
        <%= link_to "Go Beyond", planets_path, class: "btn-blue newly-added" %>
        </p>
        </div>
    </div>
    <div class="planet_two granim-gradient newly-added"></div>
</div>

app/views/planets/index.html.erb
<div class="banner">
  <h1 class="glow-header">Galaxy Far, Far Away? Quick Trip to Mars?<br>
    Pianeta has you covered.</h1>
  <div>
    <div class="inner-form">
      <%= form_tag planets_path, method: :get do %>
        <div class="row">
          <div class="col">
            <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Find a planet",
                type: "text"  
              %>
          </div>
          <div class="col">
            <input type="text" class="form-control" placeholder="Check-in">
          </div>
          <div class="col">
            <input type="text" class="form-control" placeholder="Check-out">
          </div>
          <div class="col">
            <input type="text" class="form-control" placeholder="Space Travellers">
          </div>
          <div class="col">
            <%= submit_tag "Search", class: "btn btn-flat"%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>
<br>
<div class= "container-sm">
  <h2>Featured Planets:</h2>
</div>
<br>
<div class= "container">
  <div class="row ">
    <%# <div class="col"> %>
    <% @planets.each do |planet| %>
      <% if planet.photos.attached? %>
        <%= link_to planet_path(planet), class:'text-decoration-none' do %>
          <div class="card-category-planets">
            <%= cl_image_tag planet.photos.first.key, class: 'planet-images' %>
            <div class="card-planets-body">
              <h3 class="card-planet-title"><%= planet.title %></h3>
              <p class="card-planet-description">$<%=planet.price%>/ per night</p>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Pianeta Inc.
  </div>
</div>

app/views/planets/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3">
      <div class="bg-white rounded p-3 shadow confirmation mt-3 mb-3">
        <h1>List your property</h1>
        
          <%= simple_form_for @planet do |f| %>
          <div class="form-row">
            <div class="form-group col-md-6">
            <%= f.input :title, label: false, placeholder: 'Planet Name'%>
            </div>
            <div class="form-group col-md-6">
            <%= f.input :host_name, label: false, placeholder: 'Host Name' %>
            </div>
            </div>
            <div class="form-row">
            <div class="form-group col-md-6">
            <%= f.input :name_of_inhabitants, label: false, placeholder: "Name of Inhabitants"  %>
            </div>
            <div class="form-group col-md-6">
            <%= f.input :name_of_space_station, label: false, placeholder: "Name of Space Station"  %>
            </div>
            </div>
            <div class="form-row">
            <div class="form-group col-md-6">
            <%= f.input :name_of_galaxy, label: false, placeholder: "Name of Galaxy"  %>
            </div>
            <div class="form-group col-md-6">
            <%= f.input :price, label: false, placeholder: "Pricing $"  %>
            </div>
            </div>
            <%= f.input :description, as: :text, label: "Description", placeholder: "Accomodation, activites, atmosphere, climate etc.",  :input_html => { :cols => 3, :rows => 5} %>
          
        
        <%= f.input :photos, as: :file, input_html: { multiple: true }, hint: "Please upload 5 photos" %>
         <p class="text-muted">By clicking 
         <strong>'Publish'  </strong> 
          you are agreeing to our Terms & Conditions, Privacy Policy, and to received booking-related messages.
         </p>
        <%= f.button :button, "Publish", class: "button" %>
        <% end %>
      </div>
    </div> 
  
  </div>
</div>

app/views/planets/show.html.erb
  <div class="container p-5">
    <div class="d-flex justify-content-center">
      <%= cl_image_tag @planet.photos[0]&.key, class: "cover-picture"  %>
      <div class="gallery">
        <%= cl_image_tag @planet.photos[1]&.key, class: "top-middle-picture"  %>
        <%= cl_image_tag @planet.photos[2]&.key, class: "bottom-middle-picture"  %>
      </div>
      <div class="gallery">
        <%= cl_image_tag @planet.photos[3]&.key, class: "top-outer-picture"  %>
        <%= cl_image_tag @planet.photos[4]&.key, class: "bottom-outer-picture"  %>
      </div>
    </div>
    <div class="row d-flex m-3 justify-content-around">
      <div class="col-md-8 flex-grow-1">
        <div class="header">
          <div class="header-content">
            <b>
              <h3><%= @planet.title %></h3>
            </b>
            <p><i class="fab fa-reddit-alien"></i> Inhabitants: <%=@planet.name_of_inhabitants  %> <i class="fas fa-rocket ml-3"></i> Space Station: <%= @planet.name_of_space_station %></p>
            <p><i class="fas fa-star"></i> Galaxy: <%= @planet.name_of_galaxy %></p>
          </div>
          <div class="header-avatar">
            <%= cl_image_tag("wxaoh8vb1ekhhuhkkwbd", class: "avatar") %>
            <p> <small><em class="text-muted">Hosted by <br>
                  <%= @planet.host_name %></em></small></p>
          </div>
        </div>
        <hr>
        <p>Description:</p>
        <p><%= @planet.description %></p>
      </div>
      <div class="col-md-4 p-0">
        <%= render "bookings/form", booking: @booking %>
      </div>
    </div>
  </div>
  </div>
  <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Pianeta Inc.
  </div>
</div>
  

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Pianeta Inc.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <p class="navbar-logo"><i class="fas fa-meteor"></i> PIANETA</p>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

        <%= link_to "List your planet", new_planet_path, class: "btn btn-outline-primary-1 shadow-none focus-none text-decoration-none", type: "button", role: "button" %>
        <%= link_to "My Listings", planets_path, class: "btn btn-outline-primary-1 shadow-none focus-none text-decoration-none", type: "button", role: "button" %>



        <li class="nav-item dropdown">
          <%= image_tag "https://images.unsplash.com/photo-1601814933824-fd0b574dd592?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MXwxfDB8MXxhbGx8fHx8fHx8fA&ixlib=rb-1.2.1&q=80&w=1080&utm_source=unsplash_source&utm_medium=referral&utm_campaign=api-credit", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", "#", class: "dropdown-item" %>
            <%= link_to "Messages", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>